package org.apache.fineract.fastpayment.sinpe.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import lombok.Getter;
import org.apache.fineract.infrastructure.core.domain.AbstractPersistableCustom;

@Entity
@Table(name = "m_sinpe_enrollment")
@Getter
public class SinpeEnrollment extends AbstractPersistableCustom<Long> {

  /** Maximum stored phone number length from migration 049. */
  private static final int PHONE_NUMBER_LENGTH = 20;

  /** Maximum IBAN/external ID length stored for the link. */
  private static final int IBAN_LENGTH = 100;

  /** Maximum local link status length. */
  private static final int STATUS_LENGTH = 20;

  /** Maximum OTP length from the existing enrollment schema. */
  private static final int OTP_LENGTH = 10;

  /** Client that requested the SINPE enrollment. */
  @Column(name = "client_id", nullable = false)
  private Long clientId;

  /** Phone number used by the external SINPE contract. */
  @Column(name = "mobile_number", length = PHONE_NUMBER_LENGTH,
      nullable = false)
  private String mobileNumber;

  /** Whether the current phone enrollment OTP has been confirmed. */
  @Column(name = "is_verified", nullable = false)
  private boolean verified = false;

  /** Tenant-local time when the OTP was confirmed. */
  @Column(name = "verified_on")
  private LocalDateTime verifiedOn;

  /** Savings account linked to the phone number after provider confirmation. */
  @Column(name = "savings_account_id")
  private Long savingsAccountId;

  /** IBAN supplied by the Web-App and matched to the savings externalId. */
  @Column(name = "iban", length = IBAN_LENGTH)
  private String iban;

  /** Local link status for the confirmed external subscription. */
  @Column(name = "status", length = STATUS_LENGTH, nullable = false)
  private String status = "PENDING";

  /** UTC time when the local link was saved. */
  @Column(name = "linked_on_utc")
  private LocalDateTime linkedOnUtc;

  /** UTC time when the local link was removed. */
  @Column(name = "unlinked_on_utc")
  private LocalDateTime unlinkedOnUtc;

  /** OTP value generated by the existing enrollment flow. */
  @Column(name = "pending_otp", length = OTP_LENGTH)
  private String pendingOtp;

  /** Tenant-local OTP expiry from the existing enrollment flow. */
  @Column(name = "otp_expiry")
  private LocalDateTime otpExpiry;

  /** User that created the enrollment row. */
  @Column(name = "created_by")
  private Long createdBy;

  /** User that last modified the enrollment row. */
  @Column(name = "last_modified_by")
  private Long lastModifiedBy;

  protected SinpeEnrollment() {
    // Required by JPA.
  }

  /**
   * Creates an enrollment request for the existing phone OTP flow.
   *
   * @param clientIdValue client requesting enrollment
   * @param mobileNumberValue phone number being enrolled
   * @param createdByValue user creating the enrollment
   */
  public SinpeEnrollment(
      final Long clientIdValue,
      final String mobileNumberValue,
      final Long createdByValue) {
    this.clientId = clientIdValue;
    this.mobileNumber = mobileNumberValue;
    this.createdBy = createdByValue;
  }

  /**
   * Stores the active OTP generated by the existing enrollment request.
   *
   * @param otp OTP to validate later
   * @param expiry tenant-local OTP expiry
   */
  public void setPendingOtp(final String otp, final LocalDateTime expiry) {
    this.pendingOtp = otp;
    this.otpExpiry = expiry;
  }

  /**
   * Clears the active OTP after successful confirmation.
   */
  public void clearPendingOtp() {
    this.pendingOtp = null;
    this.otpExpiry = null;
  }

  /**
   * Marks the enrollment OTP as verified.
   *
   * @param when tenant-local verification time
   */
  public void markAsVerified(final LocalDateTime when) {
    this.verified = true;
    this.verifiedOn = when;
    clearPendingOtp();
  }

  /**
   * Records a provider-confirmed savings account link.
   *
   * @param savingsAccountIdValue linked savings account
   * @param ibanValue supplied IBAN
   * @param when UTC link time
   */
  public void markAsLinked(
      final Long savingsAccountIdValue,
      final String ibanValue,
      final LocalDateTime when) {
    this.savingsAccountId = savingsAccountIdValue;
    this.iban = ibanValue;
    this.status = "LINKED";
    this.linkedOnUtc = when;
    this.unlinkedOnUtc = null;
  }

  /**
   * Records a provider-confirmed delink.
   *
   * @param when UTC unlink time
   */
  public void markAsUnlinked(final LocalDateTime when) {
    this.status = "UNLINKED";
    this.unlinkedOnUtc = when;
  }

  /**
   * Checks the submitted OTP against the existing stored OTP and expiry.
   *
   * @param otp submitted OTP
   * @param now tenant-local validation time
   * @return true if the submitted OTP is still valid
   */
  public boolean isOtpValid(final String otp, final LocalDateTime now) {
    return pendingOtp != null
        && pendingOtp.equals(otp)
        && otpExpiry != null
        && !otpExpiry.isBefore(now);
  }

  /**
   * Checks whether this enrollment currently represents an active link.
   *
   * @return true if locally marked as linked
   */
  public boolean isLinked() {
    return "LINKED".equals(status);
  }
}
