package org.apache.fineract.fastpayment.sinpe.data;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SinpeCreateSubscriptionCommand {
  /** Client that owns the enrollment request. */
  private Long clientId;

  /** Phone number supported by the current SINPE provider contract. */
  private String phoneNumber;

  /** Email identifier supplied by callers but unsupported by the provider. */
  private String emailAddress;

  /** IBAN expected to match the savings account external ID. */
  private String iban;

  /** OTP generated by the existing enrollment request flow. */
  private String otp;
}
