name: Publish package to the Mifos Artifactory and GitHub Packages
on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up Java for publishing to Mifos Artifactory
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: central
          server-username: ARTIFACTORY_USERNAME
          server-password: ARTIFACTORY_PASSWORD
      - name: Publish to the Mifos Artifactory
        run: mvn -DskipITs --batch-mode deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
